import { WellbeingActivity, WellbeingRoutine, StoredPreferenceItem } from "../types";

export const DEFAULT_WELLBEING_ACTIVITIES: WellbeingActivity[] = [
  {
    id: "act-1",
    title: "10-Minute Morning Mindful Breathwork",
    domain: "mind",
    category: "Mindfulness",
    description: "A gentle box-breathing practice (4s inhale, 4s hold, 4s exhale, 4s pause) to center the nervous system and build morning clarity.",
    reason: "Supports stress reduction and improves cognitive focus before starting daily tasks.",
    energyRequired: "low",
    durationMinutes: 10,
    tags: ["breathwork", "morning", "focus", "calm"],
    locationType: "home",
  },
  {
    id: "act-2",
    title: "Outdoor Forest or Park Walk",
    domain: "body",
    category: "Nature",
    description: "Unplugged 25-minute walk in natural green space without screens. Notice 3 sounds and 3 visual textures.",
    reason: "Promotes natural circadian regulation, reduces cortisol, and restores attention.",
    energyRequired: "medium",
    durationMinutes: 25,
    tags: ["nature", "walking", "movement", "grounding"],
    locationType: "outdoors",
  },
  {
    id: "act-3",
    title: "Recreational Badminton / Racket Sport",
    domain: "body",
    category: "Movement",
    description: "A fun, active badminton match with a friend or community group focusing on agility and connection.",
    reason: "Combines cardiovascular movement, fast reflexes, and social play.",
    energyRequired: "high",
    durationMinutes: 45,
    tags: ["sports", "badminton", "cardio", "social"],
    locationType: "venue",
  },
  {
    id: "act-4",
    title: "Intentional Evening Gratitude Journaling",
    domain: "mind",
    category: "Mindfulness",
    description: "Write down 3 specific things that felt nourishing or meaningful today, noting why each mattered.",
    reason: "Strengthens positive emotional recall and transitions the mind towards restorative sleep.",
    energyRequired: "low",
    durationMinutes: 8,
    tags: ["gratitude", "reflection", "evening", "mindset"],
    locationType: "home",
  },
  {
    id: "act-5",
    title: "Mindful Tea / Coffee Slow Ritual",
    domain: "life",
    category: "Rest",
    description: "Prepare and savor a warm beverage with full sensory presence, without multitasking or checking devices.",
    reason: "Provides a cognitive reset during transitions between work or study intervals.",
    energyRequired: "low",
    durationMinutes: 15,
    tags: ["ritual", "rest", "sensory", "pause"],
    locationType: "home",
  },
  {
    id: "act-6",
    title: "Meaningful Check-In with a Friend or Family",
    domain: "connection",
    category: "Connection",
    description: "Send a genuine voice note or share an uninterrupted 15-minute call with someone you care about.",
    reason: "Nurtures interpersonal bonds and fosters mutual emotional support.",
    energyRequired: "medium",
    durationMinutes: 20,
    tags: ["connection", "relationships", "support", "community"],
    locationType: "home",
  },
  {
    id: "act-7",
    title: "Creative Freehand Sketching or Journal Doodling",
    domain: "life",
    category: "Creativity",
    description: "Express your inner landscape through colors, shapes, or stream-of-consciousness sketches without judging the output.",
    reason: "Unlocks non-verbal emotional processing and playful self-expression.",
    energyRequired: "low",
    durationMinutes: 20,
    tags: ["creativity", "art", "expression", "play"],
    locationType: "home",
  },
  {
    id: "act-8",
    title: "Evening Digital Sunset & Stretching",
    domain: "body",
    category: "Rest",
    description: "Dim bright lights 45 minutes before sleep and do gentle floor hip/spine stretches to unwind physical tension.",
    reason: "Prepares melatonin production and signals the body for deeper REM and slow-wave sleep.",
    energyRequired: "low",
    durationMinutes: 15,
    tags: ["sleep", "stretching", "unwind", "night"],
    locationType: "home",
  },
];

export const DEFAULT_ROUTINES_SEED: Omit<WellbeingRoutine, "id" | "userId">[] = [
  {
    name: "Morning Sunlight & Hydration",
    domain: "body",
    timeOfDay: "morning",
    targetTime: "07:30",
    durationMinutes: 10,
    recurrence: "daily",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    reminderEnabled: true,
    location: "Home",
    completedToday: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: "Midday Mindful Breath & Posture Check",
    domain: "mind",
    timeOfDay: "afternoon",
    targetTime: "13:00",
    durationMinutes: 5,
    recurrence: "weekdays",
    daysOfWeek: [1, 2, 3, 4, 5],
    reminderEnabled: false,
    location: "Workspace",
    completedToday: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    name: "Evening Reflection & Gratitude",
    domain: "mind",
    timeOfDay: "evening",
    targetTime: "21:30",
    durationMinutes: 10,
    recurrence: "daily",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    reminderEnabled: true,
    location: "Home",
    completedToday: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const INITIAL_STORED_PREFERENCES_SEED: StoredPreferenceItem[] = [
  {
    id: "pref-1",
    category: "interest",
    label: "Badminton & Active Sports",
    value: "Enjoys badminton and physical movement on weekends",
    confidence: "HIGH",
    source: "explicit_user",
    confirmedAt: Date.now(),
    createdAt: Date.now(),
  },
  {
    id: "pref-2",
    category: "grounding",
    label: "Nature Walks & Fresh Air",
    value: "Feels centered when spending time in parks or outdoor greenery",
    confidence: "HIGH",
    source: "explicit_user",
    confirmedAt: Date.now(),
    createdAt: Date.now(),
  },
  {
    id: "pref-3",
    category: "pattern",
    label: "Higher energy after morning movement",
    value: "Days starting with gentle movement consistently correlate with positive mood notes",
    confidence: "MEDIUM",
    source: "observed_pattern",
    createdAt: Date.now(),
  },
  {
    id: "pref-4",
    category: "hypothesis",
    label: "Potential mid-week cognitive overload",
    value: "Wednesday entries frequently mention tight deadlines and request shorter reflection modes",
    confidence: "LOW",
    source: "ai_hypothesis",
    createdAt: Date.now(),
  },
];

export const MINDFUL_INQUIRY_PROMPTS = [
  {
    id: "q-1",
    prompt: "What made me feel most fulfilled and grounded this week?",
    domain: "mind",
  },
  {
    id: "q-2",
    prompt: "When did I experience the best energy levels throughout the day?",
    domain: "body",
  },
  {
    id: "q-3",
    prompt: "What recurring challenges or friction points showed up recently?",
    domain: "life",
  },
  {
    id: "q-4",
    prompt: "Which relationships or conversations brought me true warmth and comfort?",
    domain: "connection",
  },
  {
    id: "q-5",
    prompt: "What small boundary or habit could support my wellbeing tomorrow?",
    domain: "mind",
  },
];
